version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - npm install 
      #-f --unsafe-perm=true --allow-root
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - appspec.yml
    - node_modules/
    - '**/*'
